"""parameter model

Revision ID: 322fbfef7e27
Revises: af57a4002447
Create Date: 2023-01-09 20:15:47.246864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322fbfef7e27'
down_revision = 'af57a4002447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('entity', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('sport_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sport_id'], ['Sport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Parameter')
    # ### end Alembic commands ###
