"""empty message

Revision ID: 7d29477af0c4
Revises: 
Create Date: 2022-10-14 18:09:33.101165

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '7d29477af0c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('identification_type', sa.String(length=1), nullable=False),
    sa.Column('identification_number', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('lastname', sa.String(length=128), nullable=False),
    sa.Column('cellphone', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=192), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cellphone'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('identification_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('PasswordRecovery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    role_table = sa.sql.table('Role', sa.sql.column('name', sa.String), sa.sql.column('date_created', sa.DateTime), sa.sql.column('date_modified', sa.DateTime))
    op.bulk_insert(
        role_table,
        [
            {'id': 1,'date_created': datetime.today(),'date_modified': datetime.today(), 'name': "superuser"},
            {'id': 2,'date_created': datetime.today(),'date_modified': datetime.today(), 'name': "federation"},
            {'id': 3,'date_created': datetime.today(),'date_modified': datetime.today(), 'name': "association"},
            {'id': 4,'date_created': datetime.today(),'date_modified': datetime.today(), 'name': "club"},
            {'id': 5,'date_created': datetime.today(),'date_modified': datetime.today(), 'name': "player"},
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PasswordRecovery')
    op.drop_table('User')
    op.drop_table('Role')
    # ### end Alembic commands ###
