"""sport model

Revision ID: af57a4002447
Revises: 7d29477af0c4
Create Date: 2023-01-08 21:17:19.746651

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'af57a4002447'
down_revision = '7d29477af0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    sport_table = sa.sql.table('Sport', sa.sql.column('name', sa.String), sa.sql.column('date_created', sa.DateTime), sa.sql.column('date_modified', sa.DateTime))
    op.bulk_insert(
            sport_table,
            [
                {'id': 1,'date_created': datetime.today(),'date_modified': datetime.today(), 'name': "billar"},
            ]
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sport')
    # ### end Alembic commands ###
