"""modify name parameter field

Revision ID: e0f60cbbe9b6
Revises: 322fbfef7e27
Create Date: 2023-01-09 20:54:10.790318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f60cbbe9b6'
down_revision = '322fbfef7e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Parameter', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_column('Parameter', 'entity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Parameter', sa.Column('entity', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('Parameter', 'name')
    # ### end Alembic commands ###
